---
title: "Igor Kuivjogi Fernandes"
subtitle: "Assignment 2"
# date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part A (Answers)

### a)

We cannot use OLS because $n < p + 1$ since we have $n = 59$ and $p = 401$.
  

### b)

  i) We can use $k = 3$, which has an $ELOV \approx 0.094 < 0.1$.   

  ii) The estimated regression coefficients using PCR are:
  
  $$
  \hat{\beta}_{PCR} = \begin{bmatrix}
  87.241525 & \\
  2.741935 & \\
  -2.120626 & \\
  10.388374 &
  \end{bmatrix}
  $$

  iii) $R^2 = 0.3725311$.


### c)

  i) For each step:   
  
      Step 1:    
      Maximum $(Cov[b_1^TX_{(0)}, y_{(0)}])^2 \approx 0.1385$ 

      Step 2:    
      Maximum $(Cov[b_2^TX_{(1)}, y_{(1)}])^2 \approx 0.0795$ 

      Step 3:    
      Maximum $(Cov[b_3^TX_{(2)}, y_{(2)}])^2 \approx 0.0188$  

  ii) For each step:   
  
      Step 1:   
      $R^2 \approx 0.2903$
  
      Step 2:   
      $R^2 \approx 0.9411$
  
      Step 3:   
      $R^2 \approx 0.9743$

  iii)

  iv)


### d)


# Part B (code)

```{r}
# a)
gasoline <- read.table("Gasoline_data.txt", header = T)
X <- as.matrix(gasoline[-4, -1])
y <- as.matrix(gasoline[-4, 1])
Xnew <- as.matrix(gasoline[4, -1])
ynew <- gasoline[4, 1]
n <- nrow(X)
p <- ncol(X)
```


```{r}
# b)
mu_hat <- colMeans(X)
B <- matrix(0, p, n)
for (i in 1:n) {
  B[, i] <- X[i, ] - mu_hat
}
# same as B <- apply(X, 1, function(x_i) x_i - mu_hat)
BtB <- t(B) %*% B
eigen_results <- eigen(BtB)
sum_eigen <- sum(diag(BtB))

# i)
ELOV <- array(0, n)
for (j in 1:n) {
  ELOV[j] <- 1 - sum(eigen_results$values[1:j]) / sum_eigen
}
k <- 3

# ii)
eigen_kvalues <- eigen_results$values[1:k]
eigen_kvectors <- eigen_results$vectors[, 1:k]
eigen_vectors_Sigma_hat_k <- matrix(0, p, k)
for (i in 1:k) {
  eigen_vectors_Sigma_hat_k[, i] <- c(1 / sqrt(eigen_kvalues[i])) * 
    (B %*% matrix(eigen_kvectors[, i]))
}
Ak_hat <- t(eigen_vectors_Sigma_hat_k)
Z_data <- matrix(0, n, k)
for (i in 1:n) {
  Z_data[i, ] <- Ak_hat %*% (X[i, ] - mu_hat)
}
intercept <- matrix(1, nrow = n)
rhs <- cbind(intercept, Z_data)
beta_hat_pcr <- solve(t(rhs) %*% rhs) %*% t(rhs) %*% y

# iii)
yhat_pcr <- rhs %*% beta_hat_pcr
mean_y <- mean(y)
SSR <- sum((yhat_pcr - mean_y) ^ 2)
SST <- sum((y - mean_y) ^ 2)
R2_pcr <- SSR / SST
```


```{r, eval = F}
# c)
# items i) and ii)
step <- 0
mu_Xhat <- colMeans(X)
mu_yhat <- mean(y)
TSS <- sum((y - mu_yhat) ^ 2)
y_temp <- y - mu_yhat
X_temp <- matrix(0, n, p)
for (j in 1:p) X_temp[ ,j] <- X[ ,j] - mu_Xhat[j]
B_hat <- matrix(0, p, k)
R_hat <- matrix(0, p, k)
q_hat <- matrix(0, k, 1)

estimate_Sigma_XY <- function(X_dummy, y_dummy) {
  # returns a X x Y matrix (in this case, p x 1)
  c(1 / (n - 1)) * ((t(X_dummy) - colMeans(X_dummy)) %*% (y_dummy - mean(y_dummy)))
}

# run k steps of PLS1 algorithm
for (step in 1:k) {
  Sigma_XY_hat <- estimate_Sigma_XY(X_temp, y_temp)
  b_hat <- Sigma_XY_hat / sqrt(sum(Sigma_XY_hat ^ 2))
  max_squared_cov <- sum(b_hat * Sigma_XY_hat)
  cat("Step 1", step, "\n")
  cat(paste0("Maximum (Cov[b'X_temp, y_temp])^2 = ", round(max_squared_cov, 4)), "\n")
  t_predictor <- X_temp %*% b_hat
  r_hat <- array(0, p)
  for (j in 1:p) {
    out <- lm(X_temp[ ,j] ~ 0 + t_predictor)  # no intercept
    r_hat[j] <- out$coefficients
    X_temp[ ,j] <- out$residuals  # update the j-th column of X_temp using residual
  }
  out <- lm(y_temp ~ 0 + t_predictor)  # no intercept
  q_hat_value <- out$coefficients
  y_temp <- out$residuals
  R2_pls <- 1 - (sum(y_temp ^ 2) / TSS)
  cat(paste0("R2 = ", round(R2_pls, 4), "\n\n"))
  B_hat[ , step] <- b_hat
  R_hat[ , step] <- r_hat
  q_hat[step] <- q_hat_value
}
```

